
package org.mines.douai.j2ee.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webservices.j2ee.douai.mines.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://webservices.j2ee.douai.mines.org/", className = "org.mines.douai.j2ee.webservices.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://webservices.j2ee.douai.mines.org/", className = "org.mines.douai.j2ee.webservices.SayHiResponse")
    @Action(input = "http://webservices.j2ee.douai.mines.org/HelloWorld/sayHiRequest", output = "http://webservices.j2ee.douai.mines.org/HelloWorld/sayHiResponse")
    public String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        String text);

}
